### ISSUE TITLE
ES6 target on server

### ISSUE THREAD

**Issue by hlehmann** [barbatus/typescript#27]
I tried to add the `tsconfig.json` file in the server folder but I get the following error for the server:

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```
any clue on this ?

**Comment by barbatus** [comment]
so did you read this message? the answer is in it.

**Comment by hlehmann** [comment]
According to this: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes
> Starting with TypeScript 1.8, emitted modules are always in strict mode.

So a `"use strict";` should be automaticaly emitted, isn't it ?

**Comment by barbatus** [comment]
By default `use strict` is not imposed in this package. This is due to be in accordance with Meteor's ecmascript package (Meteor code doesn't always consist of ES6 modules). So you can override it by setting `noImplicitUseStrict` to false in the main config if you want it by default (though it's not supported in the server config, probably makes sense to add it there as well).

**Comment by hlehmann** [comment]
Ok thx for the answer, no more issue with `noImplicitUseStrict:false` in the tsconfig
