### ISSUE TITLE
Regularly getting "unexpected token <"

### ISSUE THREAD

**Issue by Rhywden** [barbatus/typescript#38]
Basically, about half the time I'm saving a file I'll get the error message:

`Uncaught SyntaxError: Unexpected token <`

If I then click on the link to the offending file I'm seeing this:

![image](https://cloud.githubusercontent.com/assets/84586/21082945/62261cd6-bfe6-11e6-910c-5bc73655afe2.png)

It's perfectly fine code - it's just not transcoded. Which is exemplified by the fact that I can "fix" this issue by adding (or removing) a random number of tabs, whitespace or carriage returns. The code will then work for a while until I'm forced to remove the whitespace again if I added it before (or vice-versa).

I'm not sure where the root cause lies but it began to pop up after I updated to version 0.6.0

**Comment by csillag** [comment]
I see the same thing.
It makes normal development almost impossible.
I have also tried 0.5.5, and the situation is the same.

(Btw, what's the history? 0.5.5 was released one day after 0.6.0?)

**Comment by csillag** [comment]
Btw, version 0.5.4 seems to work fine with me.

**Comment by barbatus** [comment]
I've experienced it too. 0.5.5 is where version rolled back to 2.0.10 but path mapping is still there.
My first thought was there is some issue in the TypeScript compiler@2.1.1, since I had one strange issue with this version particularly before, also issue like this might be related https://github.com/Microsoft/TypeScript/issues/12749. Considering that 2.1.1 is a RC, it might be not stable yet.
 I am trying now to check one more time, probably will revert changed code to figure out where the origin issue is: in the package or in the compiler.

**Comment by Rhywden** [comment]
Just asking: What about upgrading to the release version 2.1.4 of TS instead?

**Comment by barbatus** [comment]
@Rhywden yes, I published 0.6.1, pease try and let me know.

**Comment by Rhywden** [comment]
Just did some tests. Doesn't seem to pop up anymore - though it was a bit random, so I'd wait a bit.

Also: I can use the spread operator for object assignments now. :)

**Comment by Rhywden** [comment]
So, I think 2+ hours of not getting this error again while coding pretty much means that the latest update solved it :)

**Comment by barbatus** [comment]
@Rhywden awesome :)
