### ISSUE TITLE
Upgrade to typescript 2.8

### ISSUE THREAD

**Issue by scharf** [barbatus/typescript#67]
The current version (`2.5.3`) is almost 3 months old. What about an upgrade to [`2.6.2`](https://github.com/Microsoft/TypeScript/releases)

**Comment by mattmccutchen** [comment]
Keeping up with TypeScript is going to be a pain.  Is there any way the build plugin could use a copy of TypeScript installed as an app-level NPM package?

In the meantime, it's possible (but a big hassle) to fork `barbatus:typescript` and `barbatus:typescript-compiler` as local packages, make a local copy of the `meteor-typescript` NPM package, change the version there, and change the local `barbatus:typescript-compiler` to point to the local `meteor-typescript` via a `file:///` URL.

**Comment by scharf** [comment]
Since [2.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) is out, I changed the title from 2.6 to 2.7

**Comment by scharf** [comment]
Since [2.8](https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/) is out, I changed the title from 2.7 to 2.8...

**Comment by Rhywden** [comment]
Hey, just an FYI: Since for some reason Barbatus is away I've finally decided to at least try to update TypeScript to the latest version by simply plonking new versions everywhere.
I don't promise wonders, new features or that it won't blow up in my face.
 As such, I'm indeed forking the whole shebang but six months are a bit of a bad sign.

**Comment by scharf** [comment]
I think, [meteor should support typescript directly](https://github.com/meteor/meteor-feature-requests/issues/285)!

**Comment by andrei-markeev** [comment]
TypeScript 2.8 introduced some really cool new features, like mapped and conditional types, so would be really great if Meteor also supported latest version of TS.

I was wondering, is it actually possible to use the TS installed in the system instead of TS embedded in the package? Maybe some switch for this... This would solve necessity to regularly update TS version in the package...

**Comment by mattmccutchen** [comment]
> I was wondering, is it actually possible to use the TS installed in the system instead of TS embedded in the package?

Then you would lose reproducibility.  It would be better to use an app-level NPM package.

**Comment by andrei-markeev** [comment]
> Then you would lose reproducibility. It would be better to use an app-level NPM package.

Yep you're right, I agree that project-scope npm package is actually better. I'm working with Meteor mostly on hobby projects so didn't think about projects where many developers are working.

Now that I think of it, it seems to be exactly as with this annoying `@babel/runtime` dependency, so probably can be implemented in similar way as the **babel-compiler** package. And would be cool if it would actually replace babel-compiler, because I think ts can do everything what babel can do anyway.

Btw, was really tired of seeing tons of errors during compilation because of old version of ts, and as a temporary fix, updated "C:\Users\%username%\AppData\Local\.meteor\packages\barbatus_typescript-compiler\0.9.12\npm\node_modules\meteor-typescript\package.json" (note: you might have different version than 0.9.12, and of course different path to .meteor if you're on Mac or Linux)

with
```
"typescript": "^2.8.1",
```

and now it works on my machine 😄

**Comment by scharf** [comment]
Thank you very much!
