### ISSUE TITLE
Is there an up-to-date example somewhere?

### ISSUE THREAD

**Issue by ndarilek** [barbatus/typescript#8]
I'm a bit confused by all the package sprawl. :) Is there an up-to-date Meteor 1.3 sample available anywhere?

I'm learning TypeScript by porting parts of my Meteor app. Unfortunately I'm getting lots of `Cannot find module ...` errors. For instance:

```
import {Meteor} from "meteor/meteor"
```

gives me this error.

I'm unsure if I need to provide an updated tsconfig.json or something for Meteor 1.3. I'm new enough to this that I'm unsure if I want to tell TS to use ES2015 modules or if Meteor's own build process handles that, if I want to emit ES2015 and let Meteor's build process take over, etc. It's also possible I'm doing something very wrong in my imports/exports, though they're suddenly all failing when they used to work fine. Having a sample project would be helpful.

Thanks.

**Comment by barbatus** [comment]
If you installed typings like:
````
npm install typings -g
typings install meteor --ambient
````
`import {Meteor} from "meteor/meteor"` won't work since Meteor declaration file is still the old one (for Meteor 1.2). Use just global `Meteor` as before.

As to the sample, you can check out TODO demo based on Angular 2 and Meteor 1.3 here https://github.com/Urigo/angular2-meteor/tree/master/examples/todos-meteor-1.3

ES2015 has nothing to do with Meteor, as well as Meteor with it. If you want though to fix ES2015, you'll need to add a `tsconfig.json` with `files` option pointing out to all the typings and ts-files you have.

More info about typings and in general, you can find out for example here http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping (read from TypeScript Typings section) and here http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure

**Comment by ndarilek** [comment]
More significantly is that I have server/lib/jobs.ts that looks like:

```
const Jobs = JobCollection("jobs")

Meteor.startup(() => Jobs.startJobServer())

export default Jobs
```

and server/tasks.js has:

```
import Jobs from "./lib/jobs"
```

and it's being told it can't find ./lib/jobs. I'm seeing this for Node 
modules, too. I've installed uuid and:

```
import uuid from "uuid"
```

gives the same error. Basically everywhere there's an import of 
anything, I get an error that the module isn't found, even if I've 
installed the typings module for that package (I.e. I have for uuid.)

Anyhow, I'll check your example, maybe I need a tsconfig.json. Thanks.

**Comment by ndarilek** [comment]
I'm a bit confused about the need to specify files in tsconfig.json. 
Aren't all .ts files automatically included by default? So wouldn't that 
include typings/main.d.ts, or are .d.ts files treated differently? I see 
the tutorial references them, but the tsconfig.json docs seem to imply 
that all *.ts files are automatically included.

Thanks for your help.

**Comment by barbatus** [comment]
Yes, Meteor processes all TypeScript files either .ts or .d.ts files indifferently.
The tutorial is a bit outdated (though, new version for Meteor 1.3 is coming soon), and mentiones previous version of the compiler. In the current version, you don't need to specify files in the config.
But it still would be helpful for those who wants to fix their IDEs (like Atom, Sublime). Setting files in the config is a way to let IDEs know about your .ts files. It's only case where it might be needed.

**Comment by barbatus** [comment]
I added ToDo demo link in the README, that's enough for now.
Let's focus other discussion at here https://github.com/barbatus/typescript/issues/9
